# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.back_button = QtWidgets.QPushButton(form)
        self.back_button.setObjectName("back_button")
        self.verticalLayout.addWidget(self.back_button, 0, QtCore.Qt.AlignLeft)
        self.help_tiltle_label = QtWidgets.QLabel(form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.help_tiltle_label.setFont(font)
        self.help_tiltle_label.setStyleSheet("")
        self.help_tiltle_label.setObjectName("help_tiltle_label")
        self.verticalLayout.addWidget(self.help_tiltle_label, 0, QtCore.Qt.AlignHCenter)
        self.help_text_label = QtWidgets.QLabel(form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.help_text_label.setFont(font)
        self.help_text_label.setStyleSheet("")
        self.help_text_label.setText("")
        self.help_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.help_text_label.setObjectName("help_text_label")
        self.verticalLayout.addWidget(self.help_text_label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 491, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Form"))
        self.back_button.setText(_translate("form", "Back"))
        self.help_tiltle_label.setText(_translate("form", "Help"))
