# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'start_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(600, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(form)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.logo = QtWidgets.QLabel(form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMaximumSize(QtCore.QSize(289, 150))
        self.logo.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo.setBaseSize(QtCore.QSize(20, 20))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("interfaces/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.start_game_button = QtWidgets.QPushButton(form)
        self.start_game_button.setObjectName("start_game_button")
        self.verticalLayout.addWidget(self.start_game_button, 0, QtCore.Qt.AlignHCenter)
        self.records_board_button = QtWidgets.QPushButton(form)
        self.records_board_button.setObjectName("records_board_button")
        self.verticalLayout.addWidget(self.records_board_button, 0, QtCore.Qt.AlignHCenter)
        self.settings_button = QtWidgets.QPushButton(form)
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout.addWidget(self.settings_button, 0, QtCore.Qt.AlignHCenter)
        self.help_button = QtWidgets.QPushButton(form)
        self.help_button.setObjectName("help_button")
        self.verticalLayout.addWidget(self.help_button, 0, QtCore.Qt.AlignHCenter)
        self.exit_button = QtWidgets.QPushButton(form)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 71, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Form"))
        self.start_game_button.setText(_translate("form", "Start"))
        self.records_board_button.setText(_translate("form", "Records"))
        self.settings_button.setText(_translate("form", "Settings"))
        self.help_button.setText(_translate("form", "Help"))
        self.exit_button.setText(_translate("form", "Exit"))
